
version: '3.2'
services:
   db:
      image: mysql
      container_name: mysqlDB
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: password123
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '80:80'
      environment:
        PMA_HOST: db